// Code generated by gen_blocks.go DO NOT EDIT.
// Package item stores information about blocks in Minecraft.
package blocks

// ID describes the numeric ID of an item.
type ID uint32

// Block describes information about a type of item.
type Block struct {
	ID          ID
	DisplayName string
	Name        string
	StackSize   uint
	Hardness    float64
	Diggable    bool
	Transparent bool
}

var (
	Air = Block{
		ID:          0,
		DisplayName: "Air",
		Name:        "air",
		StackSize:   0,
		Hardness:    0,
		Diggable:    false,
		Transparent: true,
	}
	Stone = Block{
		ID:          1,
		DisplayName: "Stone",
		Name:        "stone",
		StackSize:   64,
		Hardness:    1.5,
		Diggable:    true,
		Transparent: false,
	}
	Grass = Block{
		ID:          2,
		DisplayName: "Grass Block",
		Name:        "grass",
		StackSize:   64,
		Hardness:    0.6,
		Diggable:    true,
		Transparent: false,
	}
	Dirt = Block{
		ID:          3,
		DisplayName: "Dirt",
		Name:        "dirt",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: false,
	}
	Cobblestone = Block{
		ID:          4,
		DisplayName: "Cobblestone",
		Name:        "cobblestone",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: false,
	}
	Planks = Block{
		ID:          5,
		DisplayName: "Wood Planks",
		Name:        "planks",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: false,
	}
	Sapling = Block{
		ID:          6,
		DisplayName: "Sapling",
		Name:        "sapling",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Bedrock = Block{
		ID:          7,
		DisplayName: "Bedrock",
		Name:        "bedrock",
		StackSize:   64,
		Hardness:    0,
		Diggable:    false,
		Transparent: false,
	}
	FlowingWater = Block{
		ID:          8,
		DisplayName: "Water",
		Name:        "flowing_water",
		StackSize:   64,
		Hardness:    100,
		Diggable:    false,
		Transparent: true,
	}
	Water = Block{
		ID:          9,
		DisplayName: "Stationary Water",
		Name:        "water",
		StackSize:   64,
		Hardness:    100,
		Diggable:    false,
		Transparent: true,
	}
	FlowingLava = Block{
		ID:          10,
		DisplayName: "Lava",
		Name:        "flowing_lava",
		StackSize:   64,
		Hardness:    100,
		Diggable:    false,
		Transparent: true,
	}
	Lava = Block{
		ID:          11,
		DisplayName: "Stationary Lava",
		Name:        "lava",
		StackSize:   64,
		Hardness:    100,
		Diggable:    false,
		Transparent: true,
	}
	Sand = Block{
		ID:          12,
		DisplayName: "Sand",
		Name:        "sand",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: false,
	}
	Gravel = Block{
		ID:          13,
		DisplayName: "Gravel",
		Name:        "gravel",
		StackSize:   64,
		Hardness:    0.6,
		Diggable:    true,
		Transparent: false,
	}
	GoldOre = Block{
		ID:          14,
		DisplayName: "Gold Ore",
		Name:        "gold_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	IronOre = Block{
		ID:          15,
		DisplayName: "Iron Ore",
		Name:        "iron_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	CoalOre = Block{
		ID:          16,
		DisplayName: "Coal Ore",
		Name:        "coal_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	Log = Block{
		ID:          17,
		DisplayName: "Wood",
		Name:        "log",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: false,
	}
	Leaves = Block{
		ID:          18,
		DisplayName: "Leaves",
		Name:        "leaves",
		StackSize:   64,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: true,
	}
	Sponge = Block{
		ID:          19,
		DisplayName: "Sponge",
		Name:        "sponge",
		StackSize:   64,
		Hardness:    0.6,
		Diggable:    true,
		Transparent: false,
	}
	Glass = Block{
		ID:          20,
		DisplayName: "Glass",
		Name:        "glass",
		StackSize:   64,
		Hardness:    0.3,
		Diggable:    true,
		Transparent: true,
	}
	LapisOre = Block{
		ID:          21,
		DisplayName: "Lapis Lazuli Ore",
		Name:        "lapis_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	LapisBlock = Block{
		ID:          22,
		DisplayName: "Lapis Lazuli Block",
		Name:        "lapis_block",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	Dispenser = Block{
		ID:          23,
		DisplayName: "Dispenser",
		Name:        "dispenser",
		StackSize:   64,
		Hardness:    3.5,
		Diggable:    true,
		Transparent: false,
	}
	Sandstone = Block{
		ID:          24,
		DisplayName: "Sandstone",
		Name:        "sandstone",
		StackSize:   64,
		Hardness:    0.8,
		Diggable:    true,
		Transparent: false,
	}
	Noteblock = Block{
		ID:          25,
		DisplayName: "Note Block",
		Name:        "noteblock",
		StackSize:   64,
		Hardness:    0.8,
		Diggable:    true,
		Transparent: false,
	}
	Bed = Block{
		ID:          26,
		DisplayName: "Bed",
		Name:        "bed",
		StackSize:   1,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: true,
	}
	GoldenRail = Block{
		ID:          27,
		DisplayName: "Powered Rail",
		Name:        "golden_rail",
		StackSize:   64,
		Hardness:    0.7,
		Diggable:    true,
		Transparent: true,
	}
	DetectorRail = Block{
		ID:          28,
		DisplayName: "Detector Rail",
		Name:        "detector_rail",
		StackSize:   64,
		Hardness:    0.7,
		Diggable:    true,
		Transparent: true,
	}
	StickyPiston = Block{
		ID:          29,
		DisplayName: "Sticky Piston",
		Name:        "sticky_piston",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	Web = Block{
		ID:          30,
		DisplayName: "Cobweb",
		Name:        "web",
		StackSize:   64,
		Hardness:    4,
		Diggable:    true,
		Transparent: true,
	}
	Tallgrass = Block{
		ID:          31,
		DisplayName: "Grass",
		Name:        "tallgrass",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Deadbush = Block{
		ID:          32,
		DisplayName: "Dead Bush",
		Name:        "deadbush",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Piston = Block{
		ID:          33,
		DisplayName: "Piston",
		Name:        "piston",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	PistonHead = Block{
		ID:          34,
		DisplayName: "Piston Head",
		Name:        "piston_head",
		StackSize:   0,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: false,
	}
	Wool = Block{
		ID:          35,
		DisplayName: "Wool",
		Name:        "wool",
		StackSize:   64,
		Hardness:    0.8,
		Diggable:    true,
		Transparent: false,
	}
	PistonExtension = Block{
		ID:          36,
		DisplayName: "Block moved by Piston",
		Name:        "piston_extension",
		StackSize:   0,
		Hardness:    0,
		Diggable:    false,
		Transparent: false,
	}
	YellowFlower = Block{
		ID:          37,
		DisplayName: "Dandelion",
		Name:        "yellow_flower",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	RedFlower = Block{
		ID:          38,
		DisplayName: "Poppy",
		Name:        "red_flower",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	BrownMushroom = Block{
		ID:          39,
		DisplayName: "Brown Mushroom",
		Name:        "brown_mushroom",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	RedMushroom = Block{
		ID:          40,
		DisplayName: "Red Mushroom",
		Name:        "red_mushroom",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	GoldBlock = Block{
		ID:          41,
		DisplayName: "Block of Gold",
		Name:        "gold_block",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	IronBlock = Block{
		ID:          42,
		DisplayName: "Block of Iron",
		Name:        "iron_block",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: false,
	}
	DoubleStoneSlab = Block{
		ID:          43,
		DisplayName: "Double Stone Slab",
		Name:        "double_stone_slab",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	StoneSlab = Block{
		ID:          44,
		DisplayName: "Stone Slab",
		Name:        "stone_slab",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	BrickBlock = Block{
		ID:          45,
		DisplayName: "Bricks",
		Name:        "brick_block",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: false,
	}
	Tnt = Block{
		ID:          46,
		DisplayName: "TNT",
		Name:        "tnt",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Bookshelf = Block{
		ID:          47,
		DisplayName: "Bookshelf",
		Name:        "bookshelf",
		StackSize:   64,
		Hardness:    1.5,
		Diggable:    true,
		Transparent: false,
	}
	MossyCobblestone = Block{
		ID:          48,
		DisplayName: "Moss Stone",
		Name:        "mossy_cobblestone",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: false,
	}
	Obsidian = Block{
		ID:          49,
		DisplayName: "Obsidian",
		Name:        "obsidian",
		StackSize:   64,
		Hardness:    50,
		Diggable:    true,
		Transparent: false,
	}
	Torch = Block{
		ID:          50,
		DisplayName: "Torch",
		Name:        "torch",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Fire = Block{
		ID:          51,
		DisplayName: "Fire",
		Name:        "fire",
		StackSize:   0,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	MobSpawner = Block{
		ID:          52,
		DisplayName: "Monster Spawner",
		Name:        "mob_spawner",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: true,
	}
	OakStairs = Block{
		ID:          53,
		DisplayName: "Oak Wood Stairs",
		Name:        "oak_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	Chest = Block{
		ID:          54,
		DisplayName: "Chest",
		Name:        "chest",
		StackSize:   64,
		Hardness:    2.5,
		Diggable:    true,
		Transparent: true,
	}
	RedstoneWire = Block{
		ID:          55,
		DisplayName: "Redstone Wire",
		Name:        "redstone_wire",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	DiamondOre = Block{
		ID:          56,
		DisplayName: "Diamond Ore",
		Name:        "diamond_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	DiamondBlock = Block{
		ID:          57,
		DisplayName: "Block of Diamond",
		Name:        "diamond_block",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: false,
	}
	CraftingTable = Block{
		ID:          58,
		DisplayName: "Crafting Table",
		Name:        "crafting_table",
		StackSize:   64,
		Hardness:    2.5,
		Diggable:    true,
		Transparent: false,
	}
	Wheat = Block{
		ID:          59,
		DisplayName: "Wheat",
		Name:        "wheat",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Farmland = Block{
		ID:          60,
		DisplayName: "Farmland",
		Name:        "farmland",
		StackSize:   64,
		Hardness:    0.6,
		Diggable:    true,
		Transparent: true,
	}
	Furnace = Block{
		ID:          61,
		DisplayName: "Furnace",
		Name:        "furnace",
		StackSize:   64,
		Hardness:    3.5,
		Diggable:    true,
		Transparent: true,
	}
	LitFurnace = Block{
		ID:          62,
		DisplayName: "Burning Furnace",
		Name:        "lit_furnace",
		StackSize:   64,
		Hardness:    3.5,
		Diggable:    true,
		Transparent: true,
	}
	StandingSign = Block{
		ID:          63,
		DisplayName: "Standing Sign",
		Name:        "standing_sign",
		StackSize:   16,
		Hardness:    1,
		Diggable:    true,
		Transparent: true,
	}
	WoodenDoor = Block{
		ID:          64,
		DisplayName: "Oak Door",
		Name:        "wooden_door",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	Ladder = Block{
		ID:          65,
		DisplayName: "Ladder",
		Name:        "ladder",
		StackSize:   64,
		Hardness:    0.4,
		Diggable:    true,
		Transparent: true,
	}
	Rail = Block{
		ID:          66,
		DisplayName: "Rail",
		Name:        "rail",
		StackSize:   64,
		Hardness:    0.7,
		Diggable:    true,
		Transparent: true,
	}
	StoneStairs = Block{
		ID:          67,
		DisplayName: "Cobblestone Stairs",
		Name:        "stone_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	WallSign = Block{
		ID:          68,
		DisplayName: "Wall Sign",
		Name:        "wall_sign",
		StackSize:   16,
		Hardness:    1,
		Diggable:    true,
		Transparent: true,
	}
	Lever = Block{
		ID:          69,
		DisplayName: "Lever",
		Name:        "lever",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	StonePressurePlate = Block{
		ID:          70,
		DisplayName: "Stone Pressure Plate",
		Name:        "stone_pressure_plate",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	IronDoor = Block{
		ID:          71,
		DisplayName: "Iron Door",
		Name:        "iron_door",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: true,
	}
	WoodenPressurePlate = Block{
		ID:          72,
		DisplayName: "Wooden Pressure Plate",
		Name:        "wooden_pressure_plate",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	RedstoneOre = Block{
		ID:          73,
		DisplayName: "Redstone Ore",
		Name:        "redstone_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	LitRedstoneOre = Block{
		ID:          74,
		DisplayName: "Glowing Redstone Ore",
		Name:        "lit_redstone_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	UnlitRedstoneTorch = Block{
		ID:          75,
		DisplayName: "Redstone Torch (inactive)",
		Name:        "unlit_redstone_torch",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	RedstoneTorch = Block{
		ID:          76,
		DisplayName: "Redstone Torch (active)",
		Name:        "redstone_torch",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	StoneButton = Block{
		ID:          77,
		DisplayName: "Stone Button",
		Name:        "stone_button",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	SnowLayer = Block{
		ID:          78,
		DisplayName: "Snow (layer)",
		Name:        "snow_layer",
		StackSize:   64,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: true,
	}
	Ice = Block{
		ID:          79,
		DisplayName: "Ice",
		Name:        "ice",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	Snow = Block{
		ID:          80,
		DisplayName: "Snow",
		Name:        "snow",
		StackSize:   64,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: false,
	}
	Cactus = Block{
		ID:          81,
		DisplayName: "Cactus",
		Name:        "cactus",
		StackSize:   64,
		Hardness:    0.4,
		Diggable:    true,
		Transparent: true,
	}
	Clay = Block{
		ID:          82,
		DisplayName: "Clay",
		Name:        "clay",
		StackSize:   64,
		Hardness:    0.6,
		Diggable:    true,
		Transparent: false,
	}
	Reeds = Block{
		ID:          83,
		DisplayName: "Sugar Cane",
		Name:        "reeds",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Jukebox = Block{
		ID:          84,
		DisplayName: "Jukebox",
		Name:        "jukebox",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: false,
	}
	Fence = Block{
		ID:          85,
		DisplayName: "Fence",
		Name:        "fence",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	Pumpkin = Block{
		ID:          86,
		DisplayName: "Pumpkin",
		Name:        "pumpkin",
		StackSize:   64,
		Hardness:    1,
		Diggable:    true,
		Transparent: true,
	}
	Netherrack = Block{
		ID:          87,
		DisplayName: "Netherrack",
		Name:        "netherrack",
		StackSize:   64,
		Hardness:    0.4,
		Diggable:    true,
		Transparent: false,
	}
	SoulSand = Block{
		ID:          88,
		DisplayName: "Soul Sand",
		Name:        "soul_sand",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: false,
	}
	Glowstone = Block{
		ID:          89,
		DisplayName: "Glowstone",
		Name:        "glowstone",
		StackSize:   64,
		Hardness:    0.3,
		Diggable:    true,
		Transparent: true,
	}
	Portal = Block{
		ID:          90,
		DisplayName: "Nether Portal",
		Name:        "portal",
		StackSize:   0,
		Hardness:    0,
		Diggable:    false,
		Transparent: false,
	}
	LitPumpkin = Block{
		ID:          91,
		DisplayName: "Jack o'Lantern",
		Name:        "lit_pumpkin",
		StackSize:   64,
		Hardness:    1,
		Diggable:    true,
		Transparent: true,
	}
	Cake = Block{
		ID:          92,
		DisplayName: "Cake",
		Name:        "cake",
		StackSize:   1,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	UnpoweredRepeater = Block{
		ID:          93,
		DisplayName: "Redstone Repeater (inactive)",
		Name:        "unpowered_repeater",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	PoweredRepeater = Block{
		ID:          94,
		DisplayName: "Redstone Repeater (active)",
		Name:        "powered_repeater",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	StainedGlass = Block{
		ID:          95,
		DisplayName: "Stained Glass",
		Name:        "stained_glass",
		StackSize:   64,
		Hardness:    0.3,
		Diggable:    true,
		Transparent: true,
	}
	Trapdoor = Block{
		ID:          96,
		DisplayName: "Trapdoor",
		Name:        "trapdoor",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	MonsterEgg = Block{
		ID:          97,
		DisplayName: "Monster Egg",
		Name:        "monster_egg",
		StackSize:   64,
		Hardness:    0.75,
		Diggable:    true,
		Transparent: false,
	}
	Stonebrick = Block{
		ID:          98,
		DisplayName: "Stone Bricks",
		Name:        "stonebrick",
		StackSize:   64,
		Hardness:    1.5,
		Diggable:    true,
		Transparent: false,
	}
	BrownMushroomBlock = Block{
		ID:          99,
		DisplayName: "Brown Mushroom (block)",
		Name:        "brown_mushroom_block",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	RedMushroomBlock = Block{
		ID:          100,
		DisplayName: "Red Mushroom (block)",
		Name:        "red_mushroom_block",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	IronBars = Block{
		ID:          101,
		DisplayName: "Iron Bars",
		Name:        "iron_bars",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: true,
	}
	GlassPane = Block{
		ID:          102,
		DisplayName: "Glass Pane",
		Name:        "glass_pane",
		StackSize:   64,
		Hardness:    0.3,
		Diggable:    true,
		Transparent: true,
	}
	MelonBlock = Block{
		ID:          103,
		DisplayName: "Melon",
		Name:        "melon_block",
		StackSize:   64,
		Hardness:    1,
		Diggable:    true,
		Transparent: true,
	}
	PumpkinStem = Block{
		ID:          104,
		DisplayName: "Pumpkin Stem",
		Name:        "pumpkin_stem",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	MelonStem = Block{
		ID:          105,
		DisplayName: "Melon Stem",
		Name:        "melon_stem",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Vine = Block{
		ID:          106,
		DisplayName: "Vines",
		Name:        "vine",
		StackSize:   64,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: true,
	}
	FenceGate = Block{
		ID:          107,
		DisplayName: "Fence Gate",
		Name:        "fence_gate",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	BrickStairs = Block{
		ID:          108,
		DisplayName: "Brick Stairs",
		Name:        "brick_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	StoneBrickStairs = Block{
		ID:          109,
		DisplayName: "Stone Brick Stairs",
		Name:        "stone_brick_stairs",
		StackSize:   64,
		Hardness:    1.5,
		Diggable:    true,
		Transparent: true,
	}
	Mycelium = Block{
		ID:          110,
		DisplayName: "Mycelium",
		Name:        "mycelium",
		StackSize:   64,
		Hardness:    0.6,
		Diggable:    true,
		Transparent: false,
	}
	Waterlily = Block{
		ID:          111,
		DisplayName: "Lily Pad",
		Name:        "waterlily",
		StackSize:   64,
		Hardness:    0.6,
		Diggable:    true,
		Transparent: true,
	}
	NetherBrick = Block{
		ID:          112,
		DisplayName: "Nether Brick",
		Name:        "nether_brick",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: false,
	}
	NetherBrickFence = Block{
		ID:          113,
		DisplayName: "Nether Brick Fence",
		Name:        "nether_brick_fence",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	NetherBrickStairs = Block{
		ID:          114,
		DisplayName: "Nether Brick Stairs",
		Name:        "nether_brick_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	NetherWart = Block{
		ID:          115,
		DisplayName: "Nether Wart",
		Name:        "nether_wart",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	EnchantingTable = Block{
		ID:          116,
		DisplayName: "Enchantment Table",
		Name:        "enchanting_table",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: true,
	}
	BrewingStand = Block{
		ID:          117,
		DisplayName: "Brewing Stand",
		Name:        "brewing_stand",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	Cauldron = Block{
		ID:          118,
		DisplayName: "Cauldron",
		Name:        "cauldron",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	EndPortal = Block{
		ID:          119,
		DisplayName: "End Portal",
		Name:        "end_portal",
		StackSize:   0,
		Hardness:    0,
		Diggable:    false,
		Transparent: false,
	}
	EndPortalFrame = Block{
		ID:          120,
		DisplayName: "End Portal Block",
		Name:        "end_portal_frame",
		StackSize:   64,
		Hardness:    0,
		Diggable:    false,
		Transparent: true,
	}
	EndStone = Block{
		ID:          121,
		DisplayName: "End Stone",
		Name:        "end_stone",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	DragonEgg = Block{
		ID:          122,
		DisplayName: "Dragon Egg",
		Name:        "dragon_egg",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	RedstoneLamp = Block{
		ID:          123,
		DisplayName: "Redstone Lamp (inactive)",
		Name:        "redstone_lamp",
		StackSize:   64,
		Hardness:    0.3,
		Diggable:    true,
		Transparent: true,
	}
	LitRedstoneLamp = Block{
		ID:          124,
		DisplayName: "Redstone Lamp (active)",
		Name:        "lit_redstone_lamp",
		StackSize:   64,
		Hardness:    0.3,
		Diggable:    true,
		Transparent: true,
	}
	DoubleWoodenSlab = Block{
		ID:          125,
		DisplayName: "Double Wooden Slab",
		Name:        "double_wooden_slab",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	WoodenSlab = Block{
		ID:          126,
		DisplayName: "Wooden Slab",
		Name:        "wooden_slab",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	Cocoa = Block{
		ID:          127,
		DisplayName: "Cocoa",
		Name:        "cocoa",
		StackSize:   64,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: true,
	}
	SandstoneStairs = Block{
		ID:          128,
		DisplayName: "Sandstone Stairs",
		Name:        "sandstone_stairs",
		StackSize:   64,
		Hardness:    0.8,
		Diggable:    true,
		Transparent: true,
	}
	EmeraldOre = Block{
		ID:          129,
		DisplayName: "Emerald Ore",
		Name:        "emerald_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	EnderChest = Block{
		ID:          130,
		DisplayName: "Ender Chest",
		Name:        "ender_chest",
		StackSize:   64,
		Hardness:    22.5,
		Diggable:    true,
		Transparent: true,
	}
	TripwireHook = Block{
		ID:          131,
		DisplayName: "Tripwire Hook",
		Name:        "tripwire_hook",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Tripwire = Block{
		ID:          132,
		DisplayName: "Tripwire",
		Name:        "tripwire",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	EmeraldBlock = Block{
		ID:          133,
		DisplayName: "Block of Emerald",
		Name:        "emerald_block",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: false,
	}
	SpruceStairs = Block{
		ID:          134,
		DisplayName: "Spruce Wood Stairs",
		Name:        "spruce_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	BirchStairs = Block{
		ID:          135,
		DisplayName: "Birch Wood Stairs",
		Name:        "birch_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	JungleStairs = Block{
		ID:          136,
		DisplayName: "Jungle Wood Stairs",
		Name:        "jungle_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	CommandBlock = Block{
		ID:          137,
		DisplayName: "Command Block",
		Name:        "command_block",
		StackSize:   64,
		Hardness:    0,
		Diggable:    false,
		Transparent: false,
	}
	Beacon = Block{
		ID:          138,
		DisplayName: "Beacon",
		Name:        "beacon",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	CobblestoneWall = Block{
		ID:          139,
		DisplayName: "Cobblestone Wall",
		Name:        "cobblestone_wall",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	FlowerPot = Block{
		ID:          140,
		DisplayName: "Flower Pot",
		Name:        "flower_pot",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Carrots = Block{
		ID:          141,
		DisplayName: "Carrot",
		Name:        "carrots",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	Potatoes = Block{
		ID:          142,
		DisplayName: "Potato",
		Name:        "potatoes",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	WoodenButton = Block{
		ID:          143,
		DisplayName: "Wooden Button",
		Name:        "wooden_button",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	Skull = Block{
		ID:          144,
		DisplayName: "Mob head",
		Name:        "skull",
		StackSize:   64,
		Hardness:    1,
		Diggable:    true,
		Transparent: true,
	}
	Anvil = Block{
		ID:          145,
		DisplayName: "Anvil",
		Name:        "anvil",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: true,
	}
	TrappedChest = Block{
		ID:          146,
		DisplayName: "Trapped Chest",
		Name:        "trapped_chest",
		StackSize:   64,
		Hardness:    2.5,
		Diggable:    true,
		Transparent: true,
	}
	LightWeightedPressurePlate = Block{
		ID:          147,
		DisplayName: "Weighted Pressure Plate (Light)",
		Name:        "light_weighted_pressure_plate",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	HeavyWeightedPressurePlate = Block{
		ID:          148,
		DisplayName: "Weighted Pressure Plate (Heavy)",
		Name:        "heavy_weighted_pressure_plate",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: true,
	}
	UnpoweredComparator = Block{
		ID:          149,
		DisplayName: "Redstone Comparator",
		Name:        "unpowered_comparator",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	PoweredComparator = Block{
		ID:          150,
		DisplayName: "Redstone Comparator (deprecated)",
		Name:        "powered_comparator",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	DaylightDetector = Block{
		ID:          151,
		DisplayName: "Daylight Sensor",
		Name:        "daylight_detector",
		StackSize:   64,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: true,
	}
	RedstoneBlock = Block{
		ID:          152,
		DisplayName: "Block of Redstone",
		Name:        "redstone_block",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: true,
	}
	QuartzOre = Block{
		ID:          153,
		DisplayName: "Nether Quartz Ore",
		Name:        "quartz_ore",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: false,
	}
	Hopper = Block{
		ID:          154,
		DisplayName: "Hopper",
		Name:        "hopper",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	QuartzBlock = Block{
		ID:          155,
		DisplayName: "Block of Quartz",
		Name:        "quartz_block",
		StackSize:   64,
		Hardness:    0.8,
		Diggable:    true,
		Transparent: false,
	}
	QuartzStairs = Block{
		ID:          156,
		DisplayName: "Quartz Stairs",
		Name:        "quartz_stairs",
		StackSize:   64,
		Hardness:    0.8,
		Diggable:    true,
		Transparent: true,
	}
	ActivatorRail = Block{
		ID:          157,
		DisplayName: "Activator Rail",
		Name:        "activator_rail",
		StackSize:   64,
		Hardness:    0.7,
		Diggable:    true,
		Transparent: true,
	}
	Dropper = Block{
		ID:          158,
		DisplayName: "Dropper",
		Name:        "dropper",
		StackSize:   64,
		Hardness:    3.5,
		Diggable:    true,
		Transparent: false,
	}
	StainedHardenedClay = Block{
		ID:          159,
		DisplayName: "Stained Clay",
		Name:        "stained_hardened_clay",
		StackSize:   64,
		Hardness:    1.25,
		Diggable:    true,
		Transparent: false,
	}
	StainedGlassPane = Block{
		ID:          160,
		DisplayName: "Stained Glass Pane",
		Name:        "stained_glass_pane",
		StackSize:   64,
		Hardness:    0.3,
		Diggable:    true,
		Transparent: true,
	}
	Leaves2 = Block{
		ID:          161,
		DisplayName: "Leaves (Acacia/Dark Oak)",
		Name:        "leaves2",
		StackSize:   64,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: true,
	}
	Log2 = Block{
		ID:          162,
		DisplayName: "Wood (Acacia/Dark Oak)",
		Name:        "log2",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: false,
	}
	AcaciaStairs = Block{
		ID:          163,
		DisplayName: "Acacia Wood Stairs",
		Name:        "acacia_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	DarkOakStairs = Block{
		ID:          164,
		DisplayName: "Dark Oak Wood Stairs",
		Name:        "dark_oak_stairs",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	Slime = Block{
		ID:          165,
		DisplayName: "Slime Block",
		Name:        "slime",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: true,
	}
	Barrier = Block{
		ID:          166,
		DisplayName: "Barrier",
		Name:        "barrier",
		StackSize:   64,
		Hardness:    0,
		Diggable:    false,
		Transparent: true,
	}
	IronTrapdoor = Block{
		ID:          167,
		DisplayName: "Iron Trapdoor",
		Name:        "iron_trapdoor",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: true,
	}
	Prismarine = Block{
		ID:          168,
		DisplayName: "Prismarine",
		Name:        "prismarine",
		StackSize:   64,
		Hardness:    1.5,
		Diggable:    true,
		Transparent: false,
	}
	SeaLantern = Block{
		ID:          169,
		DisplayName: "Sea Lantern",
		Name:        "sea_lantern",
		StackSize:   64,
		Hardness:    0.3,
		Diggable:    true,
		Transparent: true,
	}
	HayBlock = Block{
		ID:          170,
		DisplayName: "Hay Bale",
		Name:        "hay_block",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: false,
	}
	Carpet = Block{
		ID:          171,
		DisplayName: "Carpet",
		Name:        "carpet",
		StackSize:   64,
		Hardness:    0.1,
		Diggable:    true,
		Transparent: true,
	}
	HardenedClay = Block{
		ID:          172,
		DisplayName: "Hardened Clay",
		Name:        "hardened_clay",
		StackSize:   64,
		Hardness:    1.25,
		Diggable:    true,
		Transparent: false,
	}
	CoalBlock = Block{
		ID:          173,
		DisplayName: "Block of Coal",
		Name:        "coal_block",
		StackSize:   64,
		Hardness:    5,
		Diggable:    true,
		Transparent: false,
	}
	PackedIce = Block{
		ID:          174,
		DisplayName: "Packed Ice",
		Name:        "packed_ice",
		StackSize:   64,
		Hardness:    0.5,
		Diggable:    true,
		Transparent: false,
	}
	DoublePlant = Block{
		ID:          175,
		DisplayName: "Large Flowers",
		Name:        "double_plant",
		StackSize:   64,
		Hardness:    0,
		Diggable:    true,
		Transparent: false,
	}
	StandingBanner = Block{
		ID:          176,
		DisplayName: "Standing Banner",
		Name:        "standing_banner",
		StackSize:   16,
		Hardness:    1,
		Diggable:    true,
		Transparent: true,
	}
	WallBanner = Block{
		ID:          177,
		DisplayName: "Wall Banner",
		Name:        "wall_banner",
		StackSize:   16,
		Hardness:    1,
		Diggable:    true,
		Transparent: true,
	}
	DaylightDetectorInverted = Block{
		ID:          178,
		DisplayName: "Inverted Daylight Sensor",
		Name:        "daylight_detector_inverted",
		StackSize:   64,
		Hardness:    0.2,
		Diggable:    true,
		Transparent: true,
	}
	RedSandstone = Block{
		ID:          179,
		DisplayName: "Red Sandstone",
		Name:        "red_sandstone",
		StackSize:   64,
		Hardness:    0.8,
		Diggable:    true,
		Transparent: false,
	}
	RedSandstoneStairs = Block{
		ID:          180,
		DisplayName: "Red Sandstone Stairs",
		Name:        "red_sandstone_stairs",
		StackSize:   64,
		Hardness:    0.8,
		Diggable:    true,
		Transparent: true,
	}
	DoubleStoneSlab2 = Block{
		ID:          181,
		DisplayName: "Double Red Sandstone Slab",
		Name:        "double_stone_slab2",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	StoneSlab2 = Block{
		ID:          182,
		DisplayName: "Red Sandstone Slab",
		Name:        "stone_slab2",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	SpruceFenceGate = Block{
		ID:          183,
		DisplayName: "Spruce Fence Gate",
		Name:        "spruce_fence_gate",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	BirchFenceGate = Block{
		ID:          184,
		DisplayName: "Birch Fence Gate",
		Name:        "birch_fence_gate",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	JungleFenceGate = Block{
		ID:          185,
		DisplayName: "Jungle Fence Gate",
		Name:        "jungle_fence_gate",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	DarkOakFenceGate = Block{
		ID:          186,
		DisplayName: "Dark Oak Fence Gate",
		Name:        "dark_oak_fence_gate",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	AcaciaFenceGate = Block{
		ID:          187,
		DisplayName: "Acacia Fence Gate",
		Name:        "acacia_fence_gate",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	SpruceFence = Block{
		ID:          188,
		DisplayName: "Spruce Fence",
		Name:        "spruce_fence",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	BirchFence = Block{
		ID:          189,
		DisplayName: "Birch Fence",
		Name:        "birch_fence",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	JungleFence = Block{
		ID:          190,
		DisplayName: "Jungle Fence",
		Name:        "jungle_fence",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	DarkOakFence = Block{
		ID:          191,
		DisplayName: "Dark Oak Fence",
		Name:        "dark_oak_fence",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	AcaciaFence = Block{
		ID:          192,
		DisplayName: "Acacia Fence",
		Name:        "acacia_fence",
		StackSize:   64,
		Hardness:    2,
		Diggable:    true,
		Transparent: true,
	}
	SpruceDoor = Block{
		ID:          193,
		DisplayName: "Spruce Door",
		Name:        "spruce_door",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	BirchDoor = Block{
		ID:          194,
		DisplayName: "Birch Door",
		Name:        "birch_door",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	JungleDoor = Block{
		ID:          195,
		DisplayName: "Jungle Door",
		Name:        "jungle_door",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	AcaciaDoor = Block{
		ID:          196,
		DisplayName: "Acacia Door",
		Name:        "acacia_door",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
	DarkOakDoor = Block{
		ID:          197,
		DisplayName: "Dark Oak Door",
		Name:        "dark_oak_door",
		StackSize:   64,
		Hardness:    3,
		Diggable:    true,
		Transparent: true,
	}
)

// ByID is an index of minecraft blocks by their ID.
var ByID = map[ID]*Block{
	0:   &Air,
	1:   &Stone,
	2:   &Grass,
	3:   &Dirt,
	4:   &Cobblestone,
	5:   &Planks,
	6:   &Sapling,
	7:   &Bedrock,
	8:   &FlowingWater,
	9:   &Water,
	10:  &FlowingLava,
	11:  &Lava,
	12:  &Sand,
	13:  &Gravel,
	14:  &GoldOre,
	15:  &IronOre,
	16:  &CoalOre,
	17:  &Log,
	18:  &Leaves,
	19:  &Sponge,
	20:  &Glass,
	21:  &LapisOre,
	22:  &LapisBlock,
	23:  &Dispenser,
	24:  &Sandstone,
	25:  &Noteblock,
	26:  &Bed,
	27:  &GoldenRail,
	28:  &DetectorRail,
	29:  &StickyPiston,
	30:  &Web,
	31:  &Tallgrass,
	32:  &Deadbush,
	33:  &Piston,
	34:  &PistonHead,
	35:  &Wool,
	36:  &PistonExtension,
	37:  &YellowFlower,
	38:  &RedFlower,
	39:  &BrownMushroom,
	40:  &RedMushroom,
	41:  &GoldBlock,
	42:  &IronBlock,
	43:  &DoubleStoneSlab,
	44:  &StoneSlab,
	45:  &BrickBlock,
	46:  &Tnt,
	47:  &Bookshelf,
	48:  &MossyCobblestone,
	49:  &Obsidian,
	50:  &Torch,
	51:  &Fire,
	52:  &MobSpawner,
	53:  &OakStairs,
	54:  &Chest,
	55:  &RedstoneWire,
	56:  &DiamondOre,
	57:  &DiamondBlock,
	58:  &CraftingTable,
	59:  &Wheat,
	60:  &Farmland,
	61:  &Furnace,
	62:  &LitFurnace,
	63:  &StandingSign,
	64:  &WoodenDoor,
	65:  &Ladder,
	66:  &Rail,
	67:  &StoneStairs,
	68:  &WallSign,
	69:  &Lever,
	70:  &StonePressurePlate,
	71:  &IronDoor,
	72:  &WoodenPressurePlate,
	73:  &RedstoneOre,
	74:  &LitRedstoneOre,
	75:  &UnlitRedstoneTorch,
	76:  &RedstoneTorch,
	77:  &StoneButton,
	78:  &SnowLayer,
	79:  &Ice,
	80:  &Snow,
	81:  &Cactus,
	82:  &Clay,
	83:  &Reeds,
	84:  &Jukebox,
	85:  &Fence,
	86:  &Pumpkin,
	87:  &Netherrack,
	88:  &SoulSand,
	89:  &Glowstone,
	90:  &Portal,
	91:  &LitPumpkin,
	92:  &Cake,
	93:  &UnpoweredRepeater,
	94:  &PoweredRepeater,
	95:  &StainedGlass,
	96:  &Trapdoor,
	97:  &MonsterEgg,
	98:  &Stonebrick,
	99:  &BrownMushroomBlock,
	100: &RedMushroomBlock,
	101: &IronBars,
	102: &GlassPane,
	103: &MelonBlock,
	104: &PumpkinStem,
	105: &MelonStem,
	106: &Vine,
	107: &FenceGate,
	108: &BrickStairs,
	109: &StoneBrickStairs,
	110: &Mycelium,
	111: &Waterlily,
	112: &NetherBrick,
	113: &NetherBrickFence,
	114: &NetherBrickStairs,
	115: &NetherWart,
	116: &EnchantingTable,
	117: &BrewingStand,
	118: &Cauldron,
	119: &EndPortal,
	120: &EndPortalFrame,
	121: &EndStone,
	122: &DragonEgg,
	123: &RedstoneLamp,
	124: &LitRedstoneLamp,
	125: &DoubleWoodenSlab,
	126: &WoodenSlab,
	127: &Cocoa,
	128: &SandstoneStairs,
	129: &EmeraldOre,
	130: &EnderChest,
	131: &TripwireHook,
	132: &Tripwire,
	133: &EmeraldBlock,
	134: &SpruceStairs,
	135: &BirchStairs,
	136: &JungleStairs,
	137: &CommandBlock,
	138: &Beacon,
	139: &CobblestoneWall,
	140: &FlowerPot,
	141: &Carrots,
	142: &Potatoes,
	143: &WoodenButton,
	144: &Skull,
	145: &Anvil,
	146: &TrappedChest,
	147: &LightWeightedPressurePlate,
	148: &HeavyWeightedPressurePlate,
	149: &UnpoweredComparator,
	150: &PoweredComparator,
	151: &DaylightDetector,
	152: &RedstoneBlock,
	153: &QuartzOre,
	154: &Hopper,
	155: &QuartzBlock,
	156: &QuartzStairs,
	157: &ActivatorRail,
	158: &Dropper,
	159: &StainedHardenedClay,
	160: &StainedGlassPane,
	161: &Leaves2,
	162: &Log2,
	163: &AcaciaStairs,
	164: &DarkOakStairs,
	165: &Slime,
	166: &Barrier,
	167: &IronTrapdoor,
	168: &Prismarine,
	169: &SeaLantern,
	170: &HayBlock,
	171: &Carpet,
	172: &HardenedClay,
	173: &CoalBlock,
	174: &PackedIce,
	175: &DoublePlant,
	176: &StandingBanner,
	177: &WallBanner,
	178: &DaylightDetectorInverted,
	179: &RedSandstone,
	180: &RedSandstoneStairs,
	181: &DoubleStoneSlab2,
	182: &StoneSlab2,
	183: &SpruceFenceGate,
	184: &BirchFenceGate,
	185: &JungleFenceGate,
	186: &DarkOakFenceGate,
	187: &AcaciaFenceGate,
	188: &SpruceFence,
	189: &BirchFence,
	190: &JungleFence,
	191: &DarkOakFence,
	192: &AcaciaFence,
	193: &SpruceDoor,
	194: &BirchDoor,
	195: &JungleDoor,
	196: &AcaciaDoor,
	197: &DarkOakDoor,
}
